Repository thoth-station/management-api, pull requests merged in 2018-12, with the labels that each got.

#28 Propagate debug parameter
  thoth/management_api/api_v1.py
Labels: size/XS

#29 Automatic update of dependency thoth-storages from 0.9.0 to 0.9.3
  Pipfile.lock
Labels: bot

#32 Remove old parameter limit from dependency-monkey
  thoth/management_api/api_v1.py
Labels: size/XS

#33 Pipenv requires which to be installed
  thoth/management_api/swagger.yaml
Labels: size/XS

#35 Automatic update of dependency prometheus-client from 0.4.2 to 0.5.0
  Pipfile.lock
Labels: bot

#34 Use JSON as an input for direct dependencies stack definition
  thoth/management_api/swagger.yaml
Labels: approved, size/S

#36 Automatic update of dependency prometheus-flask-exporter from 0.4.0 to 0.4.1
  Pipfile.lock
Labels: bot

#37 Automatic update of dependency requests from 2.20.1 to 2.21.0
  Pipfile.lock
Labels: bot

#39 Adjust example for dependency monkey
  thoth/management_api/swagger.yaml
Labels: size/S

#40 Update thoth-common, pin down connexion due to dependency collision
  Pipfile
  Pipfile.lock
Labels: size/S

#41 Use new setuptools by default, old break environment
  thoth/management_api/swagger.yaml
Labels: size/XS

#42 Automatic update of dependency thoth-storages from 0.9.3 to 0.9.4
  Pipfile.lock
Labels: bot

#43 Demo version resolution
  thoth/management_api/swagger.yaml
Labels: size/S, size/XS

#46 Automatic update of dependency prometheus-flask-exporter from 0.4.1 to 0.5.0
  Pipfile.lock
Labels: bot

#47 Automatic update of dependency prometheus-flask-exporter from 0.5.0 to 0.5.1
  Pipfile.lock
Labels: bot
