Repository thoth-station/management-api, pull requests merged in 2018-11, with the labels that each got.

#5 Fix schema
  thoth/management_api/swagger.yaml
Labels: approved, size/XS

#2 Token secret
  openshift/deployment-template.yaml
Labels: approved, size/S

#6 Adjust dependency monkey endpoints to reflect the current implementation
  thoth/management_api/api_v1.py
  thoth/management_api/swagger.yaml
Labels: size/S

#8 Adjust endpoint for Dependency Monkey
  thoth/management_api/api_v1.py
  thoth/management_api/configuration.py
  thoth/management_api/swagger.yaml
Labels: approved, size/M

#9 Fixes and adjustments in dependency monkey endpoint
  openshift/deployment-template.yaml
  thoth/management_api/api_v1.py
  thoth/management_api/swagger.yaml
Labels: approved, size/S

#10 Expose Amun specification on API
  thoth/management_api/swagger.yaml
Labels: size/M

#12 Expose dependency monkey reports on API
  thoth/management_api/api_v1.py
  thoth/management_api/swagger.yaml
Labels: size/M

#11 Provide hardware requirements in swagger
  thoth/management_api/swagger.yaml
Labels: approved, size/M

#15 Fix whitelisted sources propagation
  thoth/management_api/api_v1.py
Labels: size/XS

#16 Slightly refactor API endpoints
  thoth/management_api/api_v1.py
  thoth/management_api/swagger.yaml
Labels: size/L

#17 Fix parameters
  thoth/management_api/api_v1.py
  thoth/management_api/swagger.yaml
Labels: approved, size/L, size/S

#18 Propagate indexes into solver runs
  thoth/management_api/api_v1.py
Labels: approved, size/S

#21 Automatic update of dependency requests from 2.20.0 to 2.20.1
  Pipfile.lock
Labels: bot

#22 Automatic update of dependency thoth-common from 0.4.0 to 0.4.5
  Pipfile.lock
Labels: bot

#23 Automatic update of dependency thoth-storages from 0.7.2 to 0.8.0
  Pipfile.lock
Labels: bot

#24 Automatic update of dependency pytest from 3.10.0 to 4.0.1
  Pipfile.lock
Labels: bot

#19 added prometheus metric export for all things REST
  Pipfile
  Pipfile.lock
  thoth/management_api/api_v1.py
  thoth/management_api/entrypoint.py
Labels: size/L, size/XL

#26 Automatic update of dependency thoth-common from 0.4.5 to 0.4.6
  Pipfile.lock
Labels: bot
