Repository thoth-station/management-api, pull requests merged in 2019-11, with the labels that each got.

#272 Fix Wrong API Call
  thoth/management_api/api_v1.py
Labels: approved, size/XS

#273 Automatic update of dependency thoth-storages from 0.19.14 to 0.19.15
  Pipfile.lock
Labels: bot

#274 Automatic update of dependency grpcio from 1.24.3 to 1.25.0
  Pipfile.lock
Labels: bot

#275 Automatic update of dependency grpcio-tools from 1.24.3 to 1.25.0
  Pipfile.lock
Labels: bot

#276 Fix redirect to swagger UI
  thoth/management_api/openapi_server.py
Labels: approved, size/XS

#277 Automatic update of dependency thoth-storages from 0.19.15 to 0.19.17
  Pipfile.lock
Labels: bot

#278 Automatic update of dependency thoth-storages from 0.19.17 to 0.19.18
  Pipfile.lock
Labels: bot

#279 Automatic update of dependency gunicorn from 19.9.0 to 20.0.0
  Pipfile.lock
Labels: bot

#280 Provide endpoint which exposes all the Python indexes
  openapi/openapi.yaml
  thoth/management_api/api_v1.py
Labels: approved, size/M

#281 Automatic update of dependency thoth-storages from 0.19.18 to 0.19.19
  Pipfile.lock
Labels: bot

#282 Automatic update of dependency thoth-common from 0.9.14 to 0.9.15
  Pipfile.lock
Labels: bot

#283 Automatic update of dependency thoth-common from 0.9.15 to 0.9.16
  Pipfile.lock
Labels: bot, size/S

#284 Automatic update of dependency pytest from 5.2.2 to 5.2.3
  Pipfile.lock
Labels: bot, size/S

#285 Maintain one graph database instance per wsgi worker
  thoth/management_api/api_v1.py
Labels: approved, size/M

#286 Reuse graph database instance also in health checks
  thoth/management_api/api_v1.py
  thoth/management_api/openapi_server.py
Labels: approved, size/M

#287 Move graph instantiation to openapi module
  thoth/management_api/api_v1.py
  thoth/management_api/openapi_server.py
Labels: approved, size/S

#288 Automatic update of dependency pytest from 5.2.3 to 5.2.4
  Pipfile.lock
Labels: bot, size/S

#289 Correct output for error response for all queries
  thoth/management_api/api_v1.py
Labels: approved, size/XS

#290 Automatic update of dependency jsonschema from 3.1.1 to 3.2.0
  Pipfile.lock
Labels: bot, size/S

#291 Automatic update of dependency thoth-storages from 0.19.19 to 0.19.22
  Pipfile.lock
Labels: bot, size/XS

#292 Add aiocontextvars for sentry-sdk integration with aiohttp
  Pipfile
  Pipfile.lock
Labels: approved, size/M

#293 Add sentry-sdk[flask] for Sentry Flask integration
  Pipfile
  Pipfile.lock
Labels: approved, size/S

#294 Automatic update of dependency pytest from 5.2.4 to 5.3.0
  Pipfile.lock
Labels: bot, size/S

#297 Automatic update of dependency thoth-storages from 0.19.22 to 0.19.23
  Pipfile.lock
Labels: bot, size/M

#298 Automatic update of dependency thoth-storages from 0.19.23 to 0.19.24
  Pipfile.lock
Labels: bot, size/S

#299 Automatic update of dependency gunicorn from 20.0.0 to 20.0.2
  Pipfile.lock
Labels: bot, size/S

#300 Automatic update of dependency sentry-sdk from 0.13.2 to 0.13.3
  Pipfile.lock
Labels: bot, size/XS

#301 Automatic update of dependency gunicorn from 20.0.2 to 20.0.3
  Pipfile.lock
Labels: bot, size/M

#302 Automatic update of dependency sentry-sdk from 0.13.3 to 0.13.4
  Pipfile.lock
Labels: bot, size/M

#303 Automatic update of dependency pytest from 5.3.0 to 5.3.1
  Pipfile.lock
Labels: bot, size/S

#304 Automatic update of dependency gunicorn from 20.0.3 to 20.0.4
  Pipfile.lock
Labels: bot, size/XS

#305 Automatic update of dependency jaeger-client from 4.1.0 to 4.2.0
  Pipfile.lock
Labels: bot, size/S

#306 Automatic update of dependency thoth-common from 0.9.16 to 0.9.17
  Pipfile.lock
Labels: bot, size/L

#307 Automatic update of dependency thoth-common from 0.9.17 to 0.9.18
  Pipfile.lock
Labels: bot, size/M

#309 Automatic update of dependency thoth-common from 0.9.18 to 0.9.19
  Pipfile.lock
Labels: bot, size/XS

#308 Automatic update of dependency thoth-storages from 0.19.24 to 0.19.25
  Pipfile.lock
Labels: bot, size/XS
