Repository thoth-station/management-api, pull requests merged in 2019-06, with the labels that each got.

#129 Automatic update of dependency pytest from 4.5.0 to 4.6.2
  Pipfile.lock
Labels: bot

#130 Automatic update of dependency thoth-storages from 0.14.0 to 0.14.1
  Pipfile.lock
Labels: bot

#131 Automatic update of dependency thoth-common from 0.8.7 to 0.8.11
  Pipfile.lock
Labels: bot

#132 Automatic update of dependency prometheus-client from 0.6.0 to 0.7.0
  Pipfile.lock
Labels: bot

#134 Automatic update of dependency pytest from 4.6.2 to 4.6.3
  Pipfile.lock
Labels: bot

#135 Automatic update of dependency prometheus-flask-exporter from 0.8.0 to 0.8.1
  Pipfile.lock
Labels: bot

#136 Automatic update of dependency connexion from 2.2.0 to 2.3.0
  Pipfile.lock
Labels: bot

#137 Update the trigger-build job to use the latest job API
  .zuul.yaml
  openshift/buildConfig-template.yaml
Labels: approved, size/XS

#138 Automatic update of dependency thoth-common from 0.8.11 to 0.9.0
  Pipfile.lock
Labels: bot

#140 Automatic update of dependency prometheus-client from 0.7.0 to 0.7.1
  Pipfile.lock
Labels: bot

#139 Make version specifier compatible with Pipenv format
  thoth/management_api/api_v1.py
Labels: approved, size/XS

#141 Provide graph-refresh endpoint
  openapi/openapi.yaml
  thoth/management_api/api_v1.py
Labels: approved, size/M, size/S

#142 Automatic update of dependency prometheus-flask-exporter from 0.8.1 to 0.8.2
  Pipfile.lock
Labels: bot

#144 Automatic update of dependency prometheus-flask-exporter from 0.8.2 to 0.9.0
  Pipfile.lock
Labels: bot

#143 Automatic update of dependency thoth-common from 0.9.0 to 0.9.1
  Pipfile.lock
Labels: bot

#145 Automatic update of dependency thoth-storages from 0.14.1 to 0.14.2
  Pipfile.lock
Labels: bot

#146 Automatic update of dependency thoth-storages from 0.14.2 to 0.14.3
  Pipfile.lock
Labels: bot

#147 Automatic update of dependency pytest from 4.6.3 to 5.0.0
  Pipfile.lock
Labels: bot
