Repository thoth-station/management-api, pull requests merged in 2019-03, with the labels that each got.

#75 Fix wrong method name in call
  thoth/management_api/api_v1.py
Labels: approved, size/XS

#76 Expose parameter for limiting number of latest versions
  thoth/management_api/api_v1.py
  thoth/management_api/swagger.yaml
Labels: size/XS

#77 reworked the service account part
  openshift/buildConfig-template.yaml
  openshift/deployment-template.yaml
  openshift/imageStream-template.yaml
Labels: approved, size/L

#79 Increase memory requirements
  openshift/deployment-template.yaml
Labels: size/XS

#82 Fix to make updates of dependencies possible
  Pipfile
  Pipfile.lock
Labels: size/L

#85 Automatic update of dependency thoth-common from 0.7.1 to 0.8.1
  Pipfile.lock
Labels: bot

#87 Add Thoth's configuration file
  .thoth.yaml
Labels: size/S

#88 Automatic update of dependency thoth-storages from 0.9.6 to 0.9.7
  Pipfile.lock
Labels: bot

#89 Automatic update of dependency prometheus-flask-exporter from 0.6.0 to 0.7.0
  Pipfile.lock
Labels: bot

#91 Automatic update of dependency pytest from 4.3.1 to 4.4.0
  Pipfile.lock
Labels: bot
