Repository thoth-station/management-api, pull requests merged in 2019-10, with the labels that each got.

#237 Automatic update of dependency thoth-common from 0.9.10 to 0.9.11
  Pipfile.lock
Labels: bot

#239 Automatic update of dependency opentracing-instrumentation from 3.2.0 to 3.2.1
  Pipfile.lock
Labels: bot

#240 Automatic update of dependency prometheus-flask-exporter from 0.10.0 to 0.11.0
  Pipfile.lock
Labels: bot

#241 Automatic update of dependency grpcio from 1.24.0 to 1.24.1
  Pipfile.lock
Labels: bot

#242 Automatic update of dependency grpcio-tools from 1.24.0 to 1.24.1
  Pipfile.lock
Labels: bot

#243 Automatic update of dependency pytest from 5.2.0 to 5.2.1
  Pipfile.lock
Labels: bot

#238 Remove subgraph checks
  openapi/openapi.yaml
  thoth/management_api/api_v1.py
Labels: approved, size/S

#244 Automatic update of dependency thoth-common from 0.9.11 to 0.9.12
  Pipfile.lock
Labels: bot

#246 Guard info gathering with a secret
  openapi/openapi.yaml
  thoth/management_api/api_v1.py
Labels: approved, size/S

#245 Add missing import
  thoth/management_api/api_v1.py
Labels: approved, size/XS

#247 Automatic update of dependency thoth-common from 0.9.12 to 0.9.14
  Pipfile.lock
Labels: bot

#249 Add Management-API version header
  thoth/management_api/openapi_server.py
Labels: approved, size/XS

#251 Automatic update of dependency connexion from 2.3.0 to 2.4.0
  Pipfile.lock
Labels: bot, do-not-merge/needs-rebase

#252 Automatic update of dependency thoth-storages from 0.19.9 to 0.19.10
  Pipfile.lock
Labels: bot, do-not-merge/needs-rebase

#253 Automatic update of dependency grpcio from 1.24.1 to 1.24.3
  Pipfile.lock
Labels: bot

#254 Automatic update of dependency grpcio-tools from 1.24.1 to 1.24.3
  Pipfile.lock
Labels: bot

#256 Add schema for Info
  Pipfile
  Pipfile.lock
  openapi/openapi.yaml
Labels: approved, size/M, size/S

#259 Provide metric for exposing schema update status
  thoth/management_api/openapi_server.py
Labels: approved, size/S

#263 Automatic update of dependency pytest from 5.2.1 to 5.2.2
  Pipfile.lock
Labels: bot

#264 Automatic update of dependency thoth-storages from 0.19.10 to 0.19.11
  Pipfile.lock
Labels: bot

#265 Automatic update of dependency thoth-storages from 0.19.11 to 0.19.12
  Pipfile.lock
Labels: bot

#260 Redirect to HTTPS instead of HTTP
  openshift/deployment-template.yaml
  thoth/management_api/openapi_server.py
Labels: approved, size/XS

#266 Do not raise exception if the service is not ready in readiness probe
  thoth/management_api/openapi_server.py
Labels: approved, size/XS

#262 Do not introduce fatal fail if database schema was removed
  thoth/management_api/openapi_server.py
Labels: approved, size/XS

#267 updated templates with annotations and param thoth-advise-value
  openshift/buildConfig-template.yaml
  openshift/deployment-template.yaml
  openshift/imageStream-template.yaml
Labels: approved, size/S

#268 Automatic update of dependency thoth-storages from 0.19.12 to 0.19.13
  Pipfile.lock
Labels: bot

#270 Automatic update of dependency thoth-storages from 0.19.13 to 0.19.14
  Pipfile.lock
Labels: bot
