Repository thoth-station/management-api, pull requests merged in 2019-12, with the labels that each got.

#310 Automatic update of dependency prometheus-flask-exporter from 0.11.0 to 0.12.1
  Pipfile.lock
Labels: bot, size/L

#311 Automatic update of dependency thoth-common from 0.9.19 to 0.9.20
  Pipfile.lock
Labels: bot, size/XS

#312 Automatic update of dependency thoth-common from 0.9.20 to 0.9.21
  Pipfile.lock
Labels: bot, size/M

#313 Automatic update of dependency sentry-sdk from 0.13.4 to 0.13.5
  Pipfile.lock
Labels: bot, size/S

#315 Automatic update of dependency thoth-storages from 0.19.25 to 0.19.26
  Pipfile.lock
Labels: bot, size/XS

#316 Automatic update of dependency thoth-storages from 0.19.26 to 0.19.27
  Pipfile.lock
Labels: bot, size/M

#317 Update Thoth configuration file and Thoth's s2i configuration
  .thoth.yaml
  .thothTemplate.yaml
  openshift/buildConfig-template.yaml
Labels: approved, size/M

#318 Initialize schema on fresh deployment based on env variable
  openshift/deployment-template.yaml
  thoth/management_api/openapi_server.py
Labels: approved, size/S

#319 Automatic update of dependency thoth-common from 0.9.21 to 0.9.22
  Pipfile.lock
Labels: bot, size/L

#320 Automatic update of dependency pytest from 5.3.1 to 5.3.2
  Pipfile.lock
Labels: bot, size/S

#322 Automatic update of dependency connexion from 2.4.0 to 2.5.0
  Pipfile.lock
Labels: bot, size/S

#323 Automatic update of dependency thoth-storages from 0.19.27 to 0.19.30
  Pipfile.lock
Labels: bot, size/M

#324 Automatic update of dependency grpcio from 1.25.0 to 1.26.0
  Pipfile.lock
Labels: bot, size/L

#325 Automatic update of dependency grpcio-tools from 1.25.0 to 1.26.0
  Pipfile.lock
Labels: bot, size/L

#326 Automatic update of dependency connexion from 2.5.0 to 2.5.1
  Pipfile.lock
Labels: bot, size/S
