Repository thoth-station/management-api, pull requests merged in 2019-09, with the labels that each got.

#207 Automatic update of dependency opentracing-instrumentation from 3.1.1 to 3.2.0
  Pipfile.lock
Labels: bot

#209 Switch from Dgraph to PostgreSQL in deployment
  openshift/deployment-template.yaml
Labels: approved, size/M

#202 Start using Thoth's base image
  .s2i/bin/assemble
  openshift/buildConfig-template.yaml
Labels: approved, size/M

#210 Add dry-run to management-API
  openapi/openapi.yaml
  thoth/management_api/api_v1.py
Labels: approved, size/S

#212 Automatic update of dependency thoth-storages from 0.18.6 to 0.19.0
  Pipfile.lock
Labels: bot

#211 Provide an endpoint for enabling and disabling a Python package index
  openapi/openapi.yaml
  thoth/management_api/api_v1.py
Labels: approved, size/M

#213 Automatic update of dependency thoth-storages from 0.19.0 to 0.19.2
  Pipfile.lock
Labels: bot

#215 Fix wring import when importing performance models
  thoth/management_api/api_v1.py
Labels: approved, size/XS

#216 Automatic update of dependency thoth-storages from 0.19.2 to 0.19.3
  Pipfile.lock
Labels: bot

#217 Provide an option to schedule solvers with transitive flag
  openapi/openapi.yaml
  thoth/management_api/api_v1.py
Labels: approved, size/S

#219 Automatic update of dependency thoth-storages from 0.19.3 to 0.19.4
  Pipfile.lock
Labels: bot

#218 Notify user about disjoint flags
  openapi/openapi.yaml
Labels: approved, size/XS

#220 Automatic update of dependency thoth-common from 0.9.8 to 0.9.9
  Pipfile.lock
Labels: bot

#221 Automatic update of dependency thoth-storages from 0.19.4 to 0.19.5
  Pipfile.lock
Labels: bot

#222 Automatic update of dependency thoth-common from 0.9.9 to 0.9.10
  Pipfile.lock
Labels: bot

#223 Automatic update of dependency pytest from 5.1.2 to 5.1.3
  Pipfile.lock
Labels: bot

#224 Automatic update of dependency thoth-storages from 0.19.5 to 0.19.6
  Pipfile.lock
Labels: bot

#225 use postgresql hostname from thoth configmap
  openshift/deployment-template.yaml
Labels: approved, size/XS

#228 Increase resources needed for deployment
  openshift/deployment-template.yaml
Labels: approved, size/L, size/XS

#229 Automatic update of dependency prometheus-flask-exporter from 0.9.1 to 0.10.0
  Pipfile.lock
Labels: bot

#230 Automatic update of dependency grpcio from 1.23.0 to 1.24.0
  Pipfile.lock
Labels: bot

#231 Automatic update of dependency grpcio-tools from 1.23.0 to 1.24.0
  Pipfile.lock
Labels: bot

#232 Automatic update of dependency thoth-storages from 0.19.7 to 0.19.8
  Pipfile.lock
Labels: bot

#234 Automatic update of dependency pytest from 5.1.3 to 5.2.0
  Pipfile.lock
Labels: bot

#236 Automatic update of dependency thoth-storages from 0.19.8 to 0.19.9
  Pipfile.lock
Labels: bot

#233 [WIP] Add Info
  openapi/openapi.yaml
  thoth/management_api/api_v1.py
Labels: approved, do-not-merge/work-in-progress, size/S
