Repository thoth-station/management-api, pull requests merged in 2019-01, with the labels that each got.

#51 raised the limits
  openshift/deployment-template.yaml
Labels: approved, size/XS

#52 Turn warning into error to have the issue reported
  thoth/management_api/configuration.py
Labels: size/XS

#44 Do not provide sources by default
  thoth/management_api/swagger.yaml
Labels: approved, size/XS

#54 Rename method to reflect semantics
  thoth/management_api/api_v1.py
Labels: size/XS

#55 Run all solvers based on recent changes in OpenShift common
  thoth/management_api/api_v1.py
Labels: size/S

#57 Automatic update of dependency pytest from 4.0.2 to 4.1.1
  Pipfile.lock
Labels: bot

#58 Automatic update of dependency thoth-common from 0.5.0 to 0.6.0
  Pipfile.lock
Labels: bot
