Repository thoth-station/management-api, pull requests merged in 2019-05, with the labels that each got.

#103 Automatic update of dependency thoth-storages from 0.11.0 to 0.11.1
  Pipfile.lock
Labels: bot

#106 Adjust erase graph endpoint for Dgraph implementation
  thoth/management_api/api_v1.py
Labels: approved, size/XS

#105 Remove sync endpoint
  thoth/management_api/api_v1.py
  thoth/management_api/swagger.yaml
Labels: size/M

#108 Use stub-api for Management API
  Pipfile
  Pipfile.lock
  openapi/openapi.yaml
  openshift/deployment-template.yaml
  thoth/management_api/api_v1.py
  thoth/management_api/configuration.py
  thoth/management_api/openapi_server.py
  thoth/management_api/swagger.yaml
Labels: size/XXL

#113 Fix coala issues
  thoth/management_api/api_v1.py
Labels: size/XS

#110 Automatic update of dependency thoth-storages from 0.11.1 to 0.11.2
  Pipfile.lock
Labels: bot

#112 Automatic update of dependency pytest from 4.4.1 to 4.4.2
  Pipfile.lock
Labels: bot

#114 Automatic update of dependency thoth-storages from 0.11.2 to 0.11.3
  Pipfile.lock
Labels: bot

#115 Automatic update of dependency thoth-storages from 0.11.3 to 0.11.4
  Pipfile.lock
Labels: bot

#116 Automatic update of dependency pytest from 4.4.2 to 4.5.0
  Pipfile.lock
Labels: bot

#118 Automatic update of dependency thoth-common from 0.8.5 to 0.8.7
  Pipfile.lock
Labels: bot

#119 Automatic update of dependency requests from 2.21.0 to 2.22.0
  Pipfile.lock
Labels: bot

#120 Automatic update of dependency flask from 1.0.2 to 1.0.3
  Pipfile.lock
Labels: bot

#121 Automatic update of dependency prometheus-flask-exporter from 0.7.2 to 0.7.3
  Pipfile.lock
Labels: bot

#122 Automatic update of dependency prometheus-flask-exporter from 0.7.3 to 0.7.4
  Pipfile.lock
Labels: bot

#123 Automatic update of dependency prometheus-flask-exporter from 0.7.4 to 0.8.0
  Pipfile.lock
Labels: bot

#126 Automatic update of dependency grpcio from 1.20.1 to 1.21.1
  Pipfile.lock
Labels: bot

#127 Automatic update of dependency grpcio-tools from 1.20.1 to 1.21.1
  Pipfile.lock
Labels: bot

#128 Automatic update of dependency thoth-storages from 0.11.4 to 0.14.0
  Pipfile.lock
Labels: bot
