Repository thoth-station/management-api, pull requests merged in 2019-02, with the labels that each got.

#62 Provide in detail info about installed solvers
  thoth/management_api/api_v1.py
Labels: size/S

#65 Automatic update of dependency pytest from 4.1.1 to 4.2.0
  Pipfile.lock
Labels: bot

#66 Automatic update of dependency pytest from 4.2.0 to 4.2.1
  Pipfile.lock
Labels: bot

#69 Automatic update of dependency thoth-common from 0.6.0 to 0.7.1
  Pipfile.lock
Labels: bot

#70 Automatic update of dependency thoth-storages from 0.9.5 to 0.9.6
  Pipfile.lock
Labels: approved, bot

#71 Automatic update of dependency prometheus-client from 0.5.0 to 0.6.0
  Pipfile.lock
Labels: bot

#72 Automatic update of dependency pytest from 4.2.1 to 4.3.0
  Pipfile.lock
Labels: bot
