Repository thoth-station/management-api, pull requests merged in 2019-07, with the labels that each got.

#148 Automatic update of dependency grpcio from 1.21.1 to 1.22.0
  Pipfile.lock
Labels: bot

#149 Automatic update of dependency grpcio-tools from 1.21.1 to 1.22.0
  Pipfile.lock
Labels: bot

#151 Automatic update of dependency flask from 1.0.3 to 1.1.0
  Pipfile.lock
Labels: bot

#152 Automatic update of dependency opentracing-instrumentation from 3.0.1 to 3.1.1
  Pipfile.lock
Labels: bot

#153 Automatic update of dependency pytest from 5.0.0 to 5.0.1
  Pipfile.lock
Labels: bot

#154 Automatic update of dependency thoth-storages from 0.14.3 to 0.14.4
  Pipfile.lock
Labels: bot

#155 Automatic update of dependency flask from 1.1.0 to 1.1.1
  Pipfile.lock
Labels: bot

#156 Automatic update of dependency thoth-storages from 0.14.4 to 0.14.5
  Pipfile.lock
Labels: bot

#157 Automatic update of dependency thoth-storages from 0.14.5 to 0.14.6
  Pipfile.lock
Labels: bot

#158 Automatic update of dependency thoth-common from 0.9.1 to 0.9.2
  Pipfile.lock
Labels: bot

#159 Automatic update of dependency thoth-storages from 0.14.6 to 0.14.7
  Pipfile.lock
Labels: bot

#150 Provide graph-sync multiple endpoint
  openapi/openapi.yaml
  thoth/management_api/api_v1.py
Labels: size/M

#160 Automatic update of dependency thoth-common from 0.9.2 to 0.9.3
  Pipfile.lock
Labels: bot

#162 Provide endpoint for checking thoth-storages version
  openapi/openapi.yaml
  thoth/management_api/api_v1.py
Labels: approved, size/S

#161 Small adjustments in API endpoints
  openapi/openapi.yaml
Labels: approved, size/S

#163 Provide endpoint for initialization of graph database instance
  openapi/openapi.yaml
  thoth/management_api/api_v1.py
Labels: approved, size/M

#166 Report back an error message if schema initialization fails
  openapi/openapi.yaml
  thoth/management_api/api_v1.py
Labels: approved, size/XS

#167 Automatic update of dependency thoth-storages from 0.14.7 to 0.14.8
  Pipfile.lock
Labels: bot

#165 Introduce endpoint for scheduling unsolvable packages
  openapi/openapi.yaml
  thoth/management_api/api_v1.py
Labels: approved, size/M

#164 Fix error on startup
  openapi/openapi.yaml
Labels: size/XS

#168 endpoint to run package analyzer jobs
  openapi/openapi.yaml
  thoth/management_api/api_v1.py
  thoth/management_api/configuration.py
Labels: approved, do-not-merge/work-in-progress, size/M

#169 Automatic update of dependency thoth-common from 0.9.3 to 0.9.4
  Pipfile.lock
Labels: bot

#171 Automatic update of dependency thoth-storages from 0.14.8 to 0.15.0
  Pipfile.lock
Labels: bot

#170 Corrected descriptions
  openapi/openapi.yaml
  thoth/management_api/api_v1.py
Labels: approved, size/XS

#172 Automatic update of dependency thoth-storages from 0.15.0 to 0.15.1
  Pipfile.lock
Labels: bot

#173 Automatic update of dependency thoth-storages from 0.15.1 to 0.15.2
  Pipfile.lock
Labels: bot

#175 Automatic dependency re-locking
  Pipfile.lock
Labels: bot, size/M

#176 Automatic update of dependency thoth-storages from 0.15.2 to 0.16.0
  Pipfile.lock
Labels: bot

#177 Automatic update of dependency thoth-storages from 0.16.0 to 0.17.0
  Pipfile.lock
Labels: bot

#178 Add identifier for inspection jobs
  openapi/openapi.yaml
Labels: approved, size/XS

#179 Automatic update of dependency thoth-storages from 0.17.0 to 0.18.0
  Pipfile.lock
Labels: bot
