Repository thoth-station/management-api, pull requests merged in 2019-08, with the labels that each got.

#180 Automatic update of dependency thoth-storages from 0.18.0 to 0.18.1
  Pipfile.lock
Labels: bot

#181 Automatic update of dependency thoth-storages from 0.18.1 to 0.18.3
  Pipfile.lock
Labels: bot

#182 Introduce endpoint for getting all the performance indicators available
  openapi/openapi.yaml
  thoth/management_api/api_v1.py
Labels: approved, size/S

#183 Add Package Analyzer log & status endpoints
  openapi/openapi.yaml
  thoth/management_api/api_v1.py
Labels: approved, size/L

#184 Fix analysis response error
  openapi/openapi.yaml
Labels: approved, size/M

#185 Automatic update of dependency thoth-common from 0.9.5 to 0.9.6
  Pipfile.lock
Labels: bot

#186 Erase is a delete operation
  openapi/openapi.yaml
Labels: approved, size/XS

#187 Add package analyzer documents to graph sync
  openapi/openapi.yaml
  thoth/management_api/api_v1.py
Labels: approved, size/XS

#188 Automatic update of dependency thoth-storages from 0.18.3 to 0.18.4
  Pipfile.lock
Labels: bot

#189 Automatic update of dependency prometheus-flask-exporter from 0.9.0 to 0.9.1
  Pipfile.lock
Labels: bot

#190 Start using Thoth in OpenShift's s2i
  .s2i/bin/assemble
  .thothTemplate.yaml
  openshift/buildConfig-template.yaml
Labels: size/M

#191 Automatic update of dependency thoth-storages from 0.18.4 to 0.18.5
  Pipfile.lock
Labels: bot

#192 Stop using extras in thoth-common
  Pipfile
  Pipfile.lock
Labels: size/XL

#193 Initial dependency lock
  Pipfile.lock
Labels: bot, size/XL

#194 Automatic update of dependency thoth-common from 0.9.7 to 0.9.8
  Pipfile.lock
Labels: bot

#195 Automatic update of dependency thoth-storages from 0.18.5 to 0.18.6
  Pipfile.lock
Labels: bot

#196 Added config
  .thoth.yaml
Labels: approved, size/S

#197 Automatic update of dependency grpcio from 1.22.0 to 1.22.1
  Pipfile.lock
Labels: bot

#199 Automatic update of dependency grpcio from 1.22.1 to 1.23.0
  Pipfile.lock
Labels: bot

#200 Automatic update of dependency grpcio-tools from 1.22.0 to 1.23.0
  Pipfile.lock
Labels: bot

#201 Automatic update of dependency pytest from 5.0.1 to 5.1.0
  Pipfile.lock
Labels: bot

#203 Automatic update of dependency pytest from 5.1.0 to 5.1.1
  Pipfile.lock
Labels: bot

#205 Automatic update of dependency pytest from 5.1.1 to 5.1.2
  Pipfile.lock
Labels: bot

#206 Automatic update of dependency jaeger-client from 4.0.0 to 4.1.0
  Pipfile.lock
Labels: bot
