Repository thoth-station/management-api, pull requests merged in 2020-01, with the labels that each got.

#327 Automatic update of dependency thoth-storages from 0.19.30 to 0.20.0
  Pipfile.lock
Labels: bot, size/L

#328 Automatic update of dependency thoth-storages from 0.20.0 to 0.20.1
  Pipfile.lock
Labels: bot, size/S

#329 Happy new year!
  thoth/management_api/api_v1.py
  thoth/management_api/configuration.py
  thoth/management_api/exceptions.py
  thoth/management_api/openapi_server.py
Labels: size/XS

#330 Automatic update of dependency thoth-storages from 0.20.1 to 0.20.2
  Pipfile.lock
Labels: bot, size/XS

#331 Automatic update of dependency thoth-storages from 0.20.2 to 0.20.3
  Pipfile.lock
Labels: bot, size/S

#332 Automatic update of dependency thoth-storages from 0.20.3 to 0.20.4
  Pipfile.lock
Labels: bot, size/XS

#333 Automatic update of dependency thoth-storages from 0.20.4 to 0.20.5
  Pipfile.lock
Labels: bot, size/M

#334 Automatic update of dependency thoth-common from 0.9.22 to 0.9.23
  Pipfile.lock
Labels: bot, size/XS

#335 Do not run adviser from bc in debug mode
  openshift/buildConfig-template.yaml
Labels: approved, size/XS

#336 Automatic update of dependency thoth-storages from 0.20.5 to 0.20.6
  Pipfile.lock
Labels: bot, size/S

#337 Automatic update of dependency sentry-sdk from 0.13.5 to 0.14.0
  Pipfile.lock
Labels: bot, size/XS

#338 Automatic update of dependency thoth-storages from 0.20.6 to 0.21.0
  Pipfile.lock
Labels: bot, size/M

#339 Add runtime environment parameter to dependency monkey endpoint
  openapi/openapi.yaml
  thoth/management_api/api_v1.py
Labels: approved, size/S

#340 Automatic update of dependency thoth-common from 0.9.23 to 0.9.24
  Pipfile.lock
Labels: bot, size/XS

#341 Automatic update of dependency thoth-storages from 0.21.0 to 0.21.1
  Pipfile.lock
Labels: bot, size/XS

#342 Automatic update of dependency thoth-storages from 0.21.1 to 0.21.2
  Pipfile.lock
Labels: bot, size/XS

#343 Automatic update of dependency thoth-storages from 0.21.2 to 0.21.3
  Pipfile.lock
Labels: bot, size/XS

#344 Consider only enabled Python package indexes
  thoth/management_api/api_v1.py
Labels: approved, size/XS

#345 Automatic update of dependency thoth-storages from 0.21.3 to 0.21.4
  Pipfile.lock
Labels: bot, size/M

#347 Automatic update of dependency thoth-storages from 0.21.4 to 0.21.5
  Pipfile.lock
Labels: bot, size/S

#348 Automatic update of dependency thoth-common from 0.9.24 to 0.9.25
  Pipfile.lock
Labels: bot, size/XS

#349 Automatic update of dependency thoth-storages from 0.21.5 to 0.21.6
  Pipfile.lock
Labels: bot, size/S

#350 Automatic update of dependency thoth-common from 0.9.25 to 0.9.26
  Pipfile.lock
Labels: bot, size/S

#351 Automatic update of dependency jaeger-client from 4.2.0 to 4.3.0
  Pipfile.lock
Labels: bot, size/S

#346 Add a way to expose pipeline configuration
  openapi/openapi.yaml
  thoth/management_api/api_v1.py
Labels: approved, size/S

#352 Automatic update of dependency thoth-storages from 0.21.6 to 0.21.7
  Pipfile.lock
Labels: bot, size/M

#353 Fix runtime environment handling
  thoth/management_api/api_v1.py
Labels: size/XS

#354 Add default value to software stacks generated
  openapi/openapi.yaml
Labels: approved, size/XS

#355 Automatic update of dependency thoth-common from 0.9.26 to 0.9.27
  Pipfile.lock
Labels: bot, size/M

#356 Show python_packages section in Amun context
  openapi/openapi.yaml
Labels: approved, size/XS

#358 Fix OpenAPI specification
  openapi/openapi.yaml
Labels: approved, size/XS

#359 Automatic update of dependency thoth-common from 0.9.27 to 0.9.28
  Pipfile.lock
Labels: bot, size/XS

#360 Automatic update of dependency pytest from 5.3.2 to 5.3.3
  Pipfile.lock
Labels: bot, size/M

#361 Add an endpoint for container image analysis - internal container image
  openapi/openapi.yaml
  thoth/management_api/api_v1.py
  thoth/management_api/configuration.py
Labels: approved, size/L

#364 Automatic dependency re-locking
  Pipfile.lock
Labels: bot, size/M

#365 Automatic update of dependency thoth-storages from 0.21.8 to 0.21.9
  Pipfile.lock
Labels: bot, size/S

#367 Automatic update of dependency thoth-storages from 0.21.9 to 0.21.10
  Pipfile.lock
Labels: bot, size/S

#368 Automatic update of dependency sentry-sdk from 0.14.0 to 0.14.1
  Pipfile.lock
Labels: bot, size/M

#369 Automatic update of dependency thoth-common from 0.9.29 to 0.9.30
  Pipfile.lock
Labels: bot, size/M

#370 Automatic update of dependency thoth-common from 0.9.30 to 0.9.31
  Pipfile.lock
Labels: bot, size/XS

#371 Automatic update of dependency thoth-storages from 0.21.10 to 0.21.11
  Pipfile.lock
Labels: bot, size/XS

#372 Automatic update of dependency thoth-common from 0.9.31 to 0.10.0
  Pipfile.lock
Labels: bot, size/M

#373 Automatic update of dependency pytest from 5.3.4 to 5.3.5
  Pipfile.lock
Labels: bot, size/M

#374 Automatic update of dependency connexion from 2.5.1 to 2.6.0
  Pipfile.lock
Labels: bot, size/XS

#375 Automatic update of dependency thoth-common from 0.10.0 to 0.10.1
  Pipfile.lock
Labels: bot, size/S
