Repository thoth-station/management-api, pull requests merged in 2020-03, with the labels that each got.

#408 Add an example for filter sieve for dependency monkey runs
  openapi/openapi.yaml
Labels: approved, size/M

#409 Automatic update of dependency prometheus-flask-exporter from 0.12.2 to 0.13.0
  Pipfile.lock
Labels: bot, size/M

#410 Automatic update of dependency thoth-common from 0.10.9 to 0.10.11
  Pipfile.lock
Labels: bot, size/XS

#413 Automatic update of dependency pytest from 5.3.5 to 5.4.0
  Pipfile.lock
Labels: bot, size/S

#414 Automatic update of dependency pytest from 5.4.0 to 5.4.1
  Pipfile.lock
Labels: bot, size/S

#404 Allow additional properties in context
  openapi/openapi.yaml
Labels: approved, size/XS

#416 Automatic update of dependency thoth-common from 0.10.11 to 0.10.12
  Pipfile.lock
Labels: bot

#417 Automatic update of dependency thoth-storages from 0.22.3 to 0.22.5
  Pipfile.lock
Labels: bot, size/S

#418 Automatic update of dependency sentry-sdk from 0.14.2 to 0.14.3
  Pipfile.lock
Labels: bot, size/XS

#419 Automatic update of dependency thoth-common from 0.10.12 to 0.12.0
  Pipfile.lock
Labels: bot

#420 Automatic update of dependency thoth-common from 0.12.0 to 0.12.1
  Pipfile.lock
Labels: bot, size/S
