Repository thoth-station/management-api, pull requests merged in 2020-07, with the labels that each got.

#482 Fixed pre-commit errors
  gunicorn.conf.py
  thoth/management_api/api_v1.py
  thoth/management_api/openapi_server.py
Labels: approved, size/S

#484 Automatic update of dependency thoth-storages from 0.22.12 to 0.24.0
  Pipfile.lock
Labels: approved, bot, size/L

#485 Automatic update of dependency sentry-sdk from 0.14.4 to 0.15.1
  Pipfile.lock
Labels: approved, bot, size/L

#476 Automatic update of dependency requests from 2.23.0 to 2.24.0
  Pipfile.lock
Labels: approved, bot, size/XS

#483 Automatic update of dependency thoth-common from 0.13.9 to 0.14.0
  Pipfile.lock
Labels: approved, bot, size/XS

#474 Automatic update of dependency opentracing-instrumentation from 3.2.1 to 3.3.1
  Pipfile.lock
Labels: approved, bot, size/XS

#475 Automatic update of dependency prometheus-flask-exporter from 0.13.0 to 0.14.1
  Pipfile.lock
Labels: approved, bot, size/XS

#488 Automatic update of dependency prometheus-flask-exporter from 0.13.0 to 0.14.1
  Pipfile.lock
Labels: approved, bot, size/S

#480 Remove result-api bits
  thoth/management_api/api_v1.py
  thoth/management_api/configuration.py
Labels: approved, size/S

#490 Fix pre-commit issues
  thoth/management_api/api_v1.py
Labels: approved, size/S

#491 Automatic update of dependency thoth-common from 0.14.0 to 0.14.1
  Pipfile.lock
Labels: approved, bot, size/S

#492 Automatic update of dependency sentry-sdk from 0.15.1 to 0.16.0
  Pipfile.lock
Labels: approved, bot, size/S

#494 Remove templates handled by thoth-application
  openshift/buildConfig-template.yaml
  openshift/deployment-template.yaml
  openshift/imageStream-template.yaml
Labels: approved, size/L

#495 Automatic update of dependency thoth-storages from 0.24.0 to 0.24.2
  Pipfile.lock
Labels: approved, bot, size/S

#497 Automatic update of dependency prometheus-flask-exporter from 0.14.1 to 0.15.0
  Pipfile.lock
Labels: approved, bot, size/M

#498 Automatic update of dependency thoth-storages from 0.24.2 to 0.24.3
  Pipfile.lock
Labels: approved, bot, size/M

#499 Automatic update of dependency sentry-sdk from 0.16.0 to 0.16.1
  Pipfile.lock
Labels: approved, bot, size/M

#501 Add maintainers
  .thoth.yaml
Labels: approved, size/XS

#503 Automatic update of dependency thoth-common from 0.14.1 to 0.14.2
  Pipfile.lock
Labels: approved, bot, size/S

#504 Release of version 0.6.2
  CHANGELOG.md
  thoth/management_api/__init__.py
Labels: approved, bot, size/S

#473 Remove endpoints for graph sync job
  openapi/openapi.yaml
  thoth/management_api/api_v1.py
Labels: approved

#510 Remove latest versions restrictions
  .thoth.yaml
Labels: approved, size/XS

#509 Automatic update of dependency thoth-storages from 0.24.3 to 0.24.4
  Pipfile.lock
Labels: approved, bot, size/S

#512 Automatic update of dependency openapi-spec-validator from 0.2.8 to 0.2.9
  Pipfile.lock
Labels: approved, bot, size/M

#513 Automatic update of dependency prometheus-flask-exporter from 0.15.0 to 0.15.4
  Pipfile.lock
Labels: approved, bot, size/M

#514 Automatic update of dependency thoth-storages from 0.24.4 to 0.24.5
  Pipfile.lock
Labels: approved, bot, size/M

#515 Automatic update of dependency sentry-sdk from 0.16.1 to 0.16.2
  Pipfile.lock
Labels: approved, bot, size/M

#518 Fix parse python solve name
  thoth/management_api/api_v1.py
Labels: approved, size/XS

#519 Automatic update of dependency thoth-common from 0.14.2 to 0.15.0
  Pipfile.lock
Labels: approved, bot, size/S

#520 Provide missing platform to dependency monkey run
  openapi/openapi.yaml
Labels: approved, size/XS

#521 Automatic update of dependency pytest from 5.4.3 to 6.0.0
  Pipfile.lock
Labels: approved, bot, size/M

#522 Remove package analyzer, it has been archived
  openapi/openapi.yaml
  thoth/management_api/api_v1.py
Labels: size/L

#523 Do exact match for the given version when scheduling solvers
  thoth/management_api/api_v1.py
Labels: approved, size/XS

#524 Automatic update of dependency thoth-common from 0.15.0 to 0.16.0
  Pipfile.lock
Labels: approved, bot, size/M

#525 Automatic update of dependency thoth-storages from 0.24.5 to 0.25.0
  Pipfile.lock
Labels: approved, bot, size/M

#526 Automatic update of dependency pytest from 6.0.0 to 6.0.1
  Pipfile.lock
Labels: approved, bot, size/M

#528 Added new workflow status method
  openapi/openapi.yaml
  thoth/management_api/api_v1.py
Labels: approved, size/M
