Repository thoth-station/management-api, pull requests merged in 2020-09, with the labels that each got.

#551 Introduce a way to parametrize predictor
  openapi/openapi.yaml
  thoth/management_api/api_v1.py
Labels: approved, do-not-merge/hold, size/XS

#553 Automatic update of dependency prometheus-flask-exporter from 0.16.0 to 0.16.4
  Pipfile.lock
Labels: approved, bot, size/S

#554 Automatic update of dependency thoth-common from 0.17.0 to 0.17.1
  Pipfile.lock
Labels: approved, bot, size/S

#555 Automatic update of dependency sentry-sdk from 0.17.1 to 0.17.2
  Pipfile.lock
Labels: approved, bot, size/S

#559 Automatic update of dependency thoth-common from 0.17.1 to 0.17.2
  Pipfile.lock
Labels: approved, bot, size/XS

#552 Introduce a way to parametrize predictor on API endpoint
  openapi/openapi.yaml
  thoth/management_api/api_v1.py
Labels: size/XS

#561 Release of version 0.7.0
  CHANGELOG.md
  thoth/management_api/__init__.py
Labels: approved, bot, size/S

#562 Remove additional property configuration
  openapi/openapi.yaml
Labels: size/XS

#563 Automatic update of dependency prometheus-flask-exporter from 0.16.4 to 0.17.0
  Pipfile.lock
Labels: approved, bot, size/L

#564 Automatic update of dependency sentry-sdk from 0.17.2 to 0.17.3
  Pipfile.lock
Labels: approved, bot, size/L

#565 Automatic update of dependency thoth-common from 0.17.2 to 0.18.1
  Pipfile.lock
Labels: approved, bot, size/S

#566 Automatic update of dependency thoth-storages from 0.25.5 to 0.25.6
  Pipfile.lock
Labels: approved, bot, size/S

#567 Automatic update of dependency sentry-sdk from 0.17.2 to 0.17.4
  Pipfile.lock
Labels: approved, bot, do-not-merge/needs-rebase, size/XS

#571 Automatic update of dependency thoth-common from 0.18.1 to 0.19.0
  Pipfile.lock
Labels: approved, bot, size/S

#572 Automatic update of dependency thoth-storages from 0.25.6 to 0.25.8
  Pipfile.lock
Labels: approved, bot, size/S

#573 Automatic update of dependency sentry-sdk from 0.17.4 to 0.17.5
  Pipfile.lock
Labels: approved, bot, size/S

#574 Automatic update of dependency pytest from 6.0.1 to 6.0.2
  Pipfile.lock
Labels: approved, bot, size/S

#577 Release of version 0.7.1
  CHANGELOG.md
  thoth/management_api/__init__.py
Labels: approved, bot, size/S

#581 Automatic update of dependency thoth-storages from 0.25.8 to 0.25.11
  Pipfile.lock
Labels: approved, bot, size/L

#583 Automatic update of dependency pytest from 6.0.2 to 6.1.0
  Pipfile.lock
Labels: approved, bot, size/L

#586 Release of version 0.7.2
  CHANGELOG.md
  thoth/management_api/__init__.py
Labels: approved, bot, size/XS

#588 Automatic update of dependency thoth-storages from 0.25.11 to 0.25.13
  Pipfile.lock
Labels: approved, bot, size/S

#589 Automatic update of dependency sentry-sdk from 0.17.5 to 0.18.0
  Pipfile.lock
Labels: approved, bot, size/S

#580 Automatic update of dependency thoth-common from 0.19.0 to 0.20.0
  Pipfile.lock
Labels: approved, bot, size/XS

#593 Release of version 0.7.3
  CHANGELOG.md
  thoth/management_api/__init__.py
Labels: approved, bot, size/XS

#592 Automatic update of dependency thoth-storages from 0.25.13 to 0.25.14
  Pipfile.lock
Labels: approved, bot, size/S
