Repository thoth-station/management-api, pull requests merged in 2020-02, with the labels that each got.

#376 Automatic update of dependency thoth-common from 0.10.1 to 0.10.2
  Pipfile.lock
Labels: bot, size/XS

#377 Automatic update of dependency grpcio from 1.26.0 to 1.27.0
  Pipfile.lock
Labels: bot, size/L

#378 Automatic update of dependency grpcio-tools from 1.26.0 to 1.27.0
  Pipfile.lock
Labels: bot, size/M

#381 Automatic dependency re-locking
  Pipfile.lock
Labels: bot, size/L

#382 Automatic update of dependency thoth-common from 0.10.2 to 0.10.3
  Pipfile.lock
Labels: bot, size/XS

#383 Automatic update of dependency thoth-common from 0.10.3 to 0.10.4
  Pipfile.lock
Labels: bot, size/XS

#384 Automatic update of dependency thoth-common from 0.10.4 to 0.10.5
  Pipfile.lock
Labels: bot, size/M

#385 Automatic update of dependency grpcio from 1.26.0 to 1.27.1
  Pipfile.lock
Labels: bot, size/L

#386 Automatic update of dependency grpcio-tools from 1.26.0 to 1.27.1
  Pipfile.lock
Labels: bot, size/L

#387 Automatic update of dependency prometheus-flask-exporter from 0.12.1 to 0.12.2
  Pipfile.lock
Labels: bot, size/XS

#389 Automatic update of dependency thoth-storages from 0.21.11 to 0.22.0
  Pipfile.lock
Labels: bot, size/S

#388 Update .thoth.yaml
  .thoth.yaml
Labels: approved, size/S

#390 Automatic update of dependency thoth-storages from 0.22.0 to 0.22.1
  Pipfile.lock
Labels: bot, size/S

#391 Automatic update of dependency thoth-common from 0.10.5 to 0.10.6
  Pipfile.lock
Labels: bot, size/XS

#393 Automatic update of dependency thoth-storages from 0.22.1 to 0.22.2
  Pipfile.lock
Labels: bot, size/S

#394 Automatic update of dependency grpcio from 1.27.1 to 1.27.2
  Pipfile.lock
Labels: bot, size/L

#395 Automatic update of dependency grpcio-tools from 1.27.1 to 1.27.2
  Pipfile.lock
Labels: bot, size/M

#392 Adjust default configuration for dependency monkey
  openapi/openapi.yaml
Labels: approved, size/M

#396 Automatic update of dependency thoth-common from 0.10.6 to 0.10.7
  Pipfile.lock
Labels: bot, size/XS

#397 Automatic update of dependency requests from 2.22.0 to 2.23.0
  Pipfile.lock
Labels: bot, size/M

#398 Automatic update of dependency thoth-common from 0.10.7 to 0.10.8
  Pipfile.lock
Labels: bot, size/M

#401 Add new parameters that can be used on Amun
  openapi/openapi.yaml
Labels: approved, size/S

#402 Add parallelism for inspection jobs
  openapi/openapi.yaml
Labels: approved, size/XS

#403 Automatic update of dependency thoth-storages from 0.22.2 to 0.22.3
  Pipfile.lock
Labels: bot

#400 Default to RHEL for dependency monkey runs
  openapi/openapi.yaml
Labels: approved, size/XS

#405 Fallback if thoth fails to give advise in bc
  openshift/buildConfig-template.yaml
Labels: approved, size/XS

#406 Automatic update of dependency sentry-sdk from 0.14.1 to 0.14.2
  Pipfile.lock
Labels: bot, size/XS

#407 Automatic update of dependency thoth-common from 0.10.8 to 0.10.9
  Pipfile.lock
Labels: bot, size/S
