Repository thoth-station/management-api, pull requests merged in 2020-10, with the labels that each got.

#598 Release of version 0.7.4
  CHANGELOG.md
  thoth/management_api/__init__.py
Labels: approved, bot, size/XS

#601 Automatic update of dependency prometheus-flask-exporter from 0.17.0 to 0.18.1
  Pipfile.lock
Labels: approved, bot, size/L

#602 Automatic update of dependency thoth-common from 0.20.0 to 0.20.1
  Pipfile.lock
Labels: approved, bot, size/L

#603 Automatic update of dependency thoth-storages from 0.25.14 to 0.25.15
  Pipfile.lock
Labels: approved, bot, size/L

#605 Automatic update of dependency sentry-sdk from 0.18.0 to 0.19.0
  Pipfile.lock
Labels: approved, bot, size/L

#608 Automatic update of dependency pytest from 6.1.0 to 6.1.1
  Pipfile.lock
Labels: approved, bot, size/XS

#600 Add optional index URL for solver analysis
  openapi/openapi.yaml
  thoth/management_api/api_v1.py
Labels: approved, size/M

#610 Do not schedule solvers if index is not enabled
  thoth/management_api/api_v1.py
Labels: approved, hacktoberfest-accepted, size/S
