Repository thoth-station/management-api, pull requests merged in 2020-06, with the labels that each got.

#464 Automatic update of dependency pytest from 5.4.2 to 5.4.3
  Pipfile.lock
Labels: bot, size/S

#463 Replicate same behavior as user-api
  thoth/management_api/openapi_server.py
Labels: approved, size/XS

#467 Release of version 0.0.2
  CHANGELOG.md
  thoth/management_api/__init__.py
Labels: bot, size/L

#469 Automatic update of dependency thoth-common from 0.13.8 to 0.13.9
  Pipfile.lock
Labels: bot, size/M

#471 Release of version 0.6.1
  CHANGELOG.md
  thoth/management_api/__init__.py
Labels: bot, size/L
