Repository thoth-station/management-api, pull requests merged in 2020-08, with the labels that each got.

#532 Automatic update of dependency thoth-common from 0.16.0 to 0.16.1
  Pipfile.lock
Labels: approved, bot, size/L

#533 Automatic update of dependency thoth-storages from 0.25.0 to 0.25.5
  Pipfile.lock
Labels: approved, bot, size/L

#534 Automatic update of dependency sentry-sdk from 0.16.2 to 0.17.0
  Pipfile.lock
Labels: approved, bot, size/L

#530 Automatic update of dependency prometheus-flask-exporter from 0.15.4 to 0.16.0
  Pipfile.lock
Labels: approved, bot, size/XS

#538 Automatic update of dependency thoth-common from 0.16.1 to 0.17.0
  Pipfile.lock
Labels: approved, bot, size/M

#531 Fix obtaining logs for DM and solvers when Argo workflows are used
  thoth/management_api/api_v1.py
Labels: size/M

#541 Release of version 0.6.3
  CHANGELOG.md
  thoth/management_api/__init__.py
Labels: approved, bot, size/M

#543 Relock dependencies due to Pipenv/Kebechet bug
  Pipfile.lock
Labels: size/M

#544 Add pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, size/S

#542 Fix typing mypy complains about typing
  thoth/management_api/api_v1.py
Labels: size/XS

#547 Release of version 0.6.4
  CHANGELOG.md
  thoth/management_api/__init__.py
Labels: approved, bot, size/XS

#548 Automatic update of dependency sentry-sdk from 0.17.0 to 0.17.1
  Pipfile.lock
Labels: approved, bot, size/L

#549 Provide service version
  thoth/management_api/openapi_server.py
Labels: size/XS

#550 Pre commit fixes
  thoth/management_api/api_v1.py
  thoth/management_api/openapi_server.py
Labels: size/S
