Repository thoth-station/management-api, pull requests merged in 2020-11, with the labels that each got.

#617 Remove unused parameters
  openapi/openapi.yaml
Labels: approved, size/XS

#614 Automatic update of dependency sentry-sdk from 0.19.0 to 0.19.1
  Pipfile.lock
Labels: approved, bot, size/L

#618 Automatic update of dependency thoth-common from 0.20.1 to 0.20.4
  Pipfile.lock
Labels: approved, bot, do-not-merge/needs-rebase, size/M

#620 Automatic update of dependency sentry-sdk from 0.19.0 to 0.19.2
  Pipfile.lock
Labels: approved, bot, do-not-merge/needs-rebase, size/M

#619 Automatic update of dependency thoth-storages from 0.25.15 to 0.25.16
  Pipfile.lock
Labels: approved, bot, do-not-merge/needs-rebase, size/XS

#621 Automatic update of dependency pytest from 6.1.1 to 6.1.2
  Pipfile.lock
Labels: approved, bot, size/M

#624 Release of version 0.8.0
  CHANGELOG.md
  thoth/management_api/__init__.py
Labels: approved, bot, size/S

#625 Openapi schema fix
  openapi/openapi.yaml
Labels: approved, size/XS

#627 Automatic update of dependency thoth-storages from 0.25.16 to 0.25.17
  Pipfile.lock
Labels: approved, bot, size/S

#629 Release of version 0.8.1
  CHANGELOG.md
  thoth/management_api/__init__.py
Labels: approved, bot, size/XS

#632 relocked pipfile
  Pipfile.lock
Labels: approved, size/XL

#634 port to python 38
  .aicoe-ci.yaml
  .thoth.yaml
  Pipfile
  Pipfile.lock
Labels: approved, size/L

#637 update aicoe yaml
  .aicoe-ci.yaml
Labels: approved, size/XS
