Repository thoth-station/management-api, pull requests merged in 2020-04, with the labels that each got.

#423 Automatic update of dependency thoth-common from 0.12.1 to 0.12.5
  Pipfile.lock
Labels: bot, size/M

#424 Automatic update of dependency thoth-storages from 0.22.5 to 0.22.7
  Pipfile.lock
Labels: bot, size/XS

#425 Automatic update of dependency thoth-common from 0.12.5 to 0.12.6
  Pipfile.lock
Labels: bot, size/XS

#426 Automatic update of dependency grpcio from 1.27.2 to 1.28.0
  Pipfile.lock
Labels: bot, size/M

#427 Automatic update of dependency grpcio-tools from 1.27.2 to 1.28.0
  Pipfile.lock
Labels: bot, size/M

#429 Automatic dependency re-locking
  Pipfile.lock
Labels: bot, size/L

#431 Automatic update of dependency grpcio from 1.27.2 to 1.28.1
  Pipfile.lock
Labels: bot, size/M

#432 Automatic update of dependency grpcio-tools from 1.27.2 to 1.28.1
  Pipfile.lock
Labels: bot, size/M

#433 Increase memory for OOM during build
  openshift/buildConfig-template.yaml
Labels: approved, size/S

#434 Increase requests for resources during the build even more
  openshift/buildConfig-template.yaml
Labels: approved, size/XS

#435 Pin grpcio to <1.28
  Pipfile
  Pipfile.lock
  openshift/buildConfig-template.yaml
Labels: approved, size/L

#436 Automatic update of dependency thoth-common from 0.12.6 to 0.12.7
  Pipfile.lock
Labels: bot, size/L

#437 Automatic update of dependency thoth-common from 0.12.7 to 0.12.8
  Pipfile.lock
Labels: bot, size/S

#438 Automatic update of dependency thoth-common from 0.12.8 to 0.12.9
  Pipfile.lock
Labels: bot, size/S

#440 Initial dependency lock
  Pipfile.lock
Labels: bot, size/XXL

#441 Automatic update of dependency thoth-common from 0.12.9 to 0.12.10
  Pipfile.lock
Labels: bot, size/M

#443 Automatic update of dependency thoth-common from 0.12.10 to 0.13.0
  Pipfile.lock
Labels: bot, size/M

#444 Automatic update of dependency connexion from 2.6.0 to 2.7.0
  Pipfile.lock
Labels: bot, size/XS

#445 Automatic update of dependency thoth-storages from 0.22.7 to 0.22.8
  Pipfile.lock
Labels: bot, size/XS

#446 Automatic update of dependency thoth-common from 0.13.0 to 0.13.1
  Pipfile.lock
Labels: bot, size/S

#447 Automatic update of dependency thoth-storages from 0.22.8 to 0.22.9
  Pipfile.lock
Labels: bot, size/S

#449 Automatic update of dependency thoth-common from 0.13.1 to 0.13.2
  Pipfile.lock
Labels: bot, size/S
