Repository thoth-station/management-api, pull requests merged in 2020-05, with the labels that each got.

#451 Automatic dependency re-locking
  Pipfile.lock
Labels: bot, size/S

#452 Automatic update of dependency pytest from 5.4.1 to 5.4.2
  Pipfile.lock
Labels: bot, size/M

#453 Automatic update of dependency thoth-storages from 0.22.9 to 0.22.10
  Pipfile.lock
Labels: bot, size/M

#454 Automatic update of dependency sentry-sdk from 0.14.3 to 0.14.4
  Pipfile.lock
Labels: bot, size/M

#455 Automatic update of dependency thoth-common from 0.13.3 to 0.13.4
  Pipfile.lock
Labels: bot, size/L

#456 Automatic update of dependency thoth-storages from 0.22.10 to 0.22.11
  Pipfile.lock
Labels: bot, size/M

#457 Automatic update of dependency thoth-common from 0.13.4 to 0.13.5
  Pipfile.lock
Labels: bot, size/XS

#458 Automatic update of dependency thoth-common from 0.13.5 to 0.13.6
  Pipfile.lock
Labels: bot, size/XS

#459 Automatic update of dependency prometheus-client from 0.7.1 to 0.8.0
  Pipfile.lock
Labels: bot, size/S

#460 Automatic update of dependency thoth-common from 0.13.6 to 0.13.7
  Pipfile.lock
Labels: bot, size/S

#461 Automatic update of dependency thoth-storages from 0.22.11 to 0.22.12
  Pipfile.lock
Labels: bot, size/M

#462 Automatic update of dependency thoth-common from 0.13.7 to 0.13.8
  Pipfile.lock
Labels: bot, size/S

#448 Remove unused environment variable
  openshift/buildConfig-template.yaml
Labels: approved, size/XS

#422 Configure logging for access log
  .coafile
  gunicorn.conf.py
  openshift/deployment-template.yaml
Labels: approved, size/XS
