Repository thoth-station/management-api, pull requests merged in 2021-06, with the labels that each got.

#757 Create endpoints for managing Python solver rules
  openapi/openapi.yaml
  thoth/management_api/api_v1.py
Labels: approved, lgtm, size/L

#763 Fix module not found error for flask._compat
  Pipfile
  Pipfile.lock
  openapi/openapi.yaml
Labels: approved, size/M

#770 Delete solver rules endpoint returns a single rule deleted
  openapi/openapi.yaml
Labels: approved, size/XS

#776 Fix wrong rule version range specified in OpenAPI spec
  openapi/openapi.yaml
Labels: approved, lgtm, size/S

#779 Adjust copyright notice in headers
  thoth/management_api/api_v1.py
  thoth/management_api/configuration.py
  thoth/management_api/exceptions.py
  thoth/management_api/openapi_server.py
Labels: approved, size/XS

#781 updates from the template project
  .github/ISSUE_TEMPLATE/major-release.md
  .github/ISSUE_TEMPLATE/minor-release.md
  .github/ISSUE_TEMPLATE/patch-release.md
  .github/ISSUE_TEMPLATE/redeliver_container_image.md
Labels: approved, bot, size/S

#782 set badges for easy access to content
  README.rst
Labels: approved, size/S

#754 Provide force_sync option when scheduling solvers
  openapi/openapi.yaml
  thoth/management_api/api_v1.py
Labels: approved, size/S
