Repository thoth-station/management-api, pull requests merged in 2022-07, with the labels that each got.

#902 Fix the description of index_url in /python/package-index/state
  openapi/openapi.yaml
Labels: approved, size/XS

#907 Get flake8 config out of pre-commit config
  .flake8
  .pre-commit-config.yaml
Labels: size/S

#908 Automatic update of base-image in CI
  .aicoe-ci.yaml
Labels: approved, size/XS, ok-to-test
