Repository thoth-station/management-api, pull requests merged in 2022-04, with the labels that each got.

#869 Update pre-commit base image version
  .prow.yaml
Labels: approved, size/XS

#868 Update dependency-monkey endpoint schema
  openapi/openapi.yaml
Labels: size/S, approved

#875 Downgrade markupsafe <2.1.0
  Pipfile
  Pipfile.lock
Labels: approved, size/L

#878 Remove requirements_locked and constraints from dependency monkey
  openapi/openapi.yaml
Labels: size/XS

#880 Add my username to approvers and maintainers
  .thoth.yaml
  OWNERS
Labels: approved, size/XS

#867 Use py38 as default in api schema
  openapi/openapi.yaml
Labels: approved, size/XS
